'''
Problem 45 - Triangular, Pentagonal, Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        T_n=n(n+1)/2        1, 3, 6, 10, 15, ...
Pentagonal      P_n=n(3n−1)/2       1, 5, 12, 22, 35, ...
Hexagonal       H_n=n(2n−1)         1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

from functools import partial
from helpers.numbers import is_triangular, is_pentagonal
from helpers.runtime import print_answer_and_elapsed_time

def next_hexagonal_pentagonal_triangular_number(previous_hexagonal_n):
    n = previous_hexagonal_n
    while True:
        n += 1
        current_number = n * (2 * n - 1)
        if is_pentagonal(current_number) and is_triangular(current_number):
            return current_number

answer = partial(next_hexagonal_pentagonal_triangular_number, 143)

if __name__ == '__main__':
    print_answer_and_elapsed_time(answer)
