version: 2
jobs:
  python:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: packages-{{ checksum "python/setup.py" }}-{{ checksum "python/requirements.txt" }}
      - run:
          name: Install
          command: |
            python -m venv venv
            . venv/bin/activate
            cd python && make install
      - save_cache:
          key: packages-{{ checksum "python/setup.py" }}-{{ checksum "python/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Test
          command: |
            . venv/bin/activate
            cd python && make test
  haskell:
    docker:
      - image: haskell:8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install
          command: cd haskell && stack setup 8.0
      - restore_cache:
          key: stack-{{ checksum "haskell/stack.yaml" }}
      - restore_cache:
          key: stack-work-{{ checksum "haskell/project-euler.cabal" }}
      - run:
          name: Test
          command: cd haskell && stack test
      - save_cache:
          key: stack-{{ checksum "haskell/stack.yaml" }}
          paths:
            - "/root/.stack"
      - save_cache:
          key: stack-work-{{ checksum "haskell/project-euler.cabal" }}
          paths:
            - "haskell/.stack-work"
workflows:
  version: 2
  python_and_haskell:
    jobs:
      - python
      - haskell
