version: 2
jobs:
  python:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: packages-{{ checksum "python/setup.py" }}-{{ checksum "python/requirements.txt" }}
      - run:
          name: Install
          command: |
            python -m venv venv
            . venv/bin/activate
            cd python && make install
      - save_cache:
          key: packages-{{ checksum "python/setup.py" }}-{{ checksum "python/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Test
          command: |
            . venv/bin/activate
            cd python && make test
  haskell:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Haskell
          command: cd haskell && docker build .
workflows:
  version: 2
  python_and_haskell:
    jobs:
      - python
      - haskell
