'''
Problem 44 - Pentagon Numbers

Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and
difference are pentagonal and D = |P_k − P_j| is minimised; what is the value
of D?
'''

from math import sqrt
from lib.helpers.numbers import is_pentagonal
from lib.helpers.runtime import print_answer_and_elapsed_time


def pentagonal_number_pair():
    n = 0
    pentagonal_numbers = []
    while True:
        n += 1
        current_number = int(n * (3 * n - 1) / 2)
        for number in pentagonal_numbers:
            total = number + current_number
            difference = current_number - number
            if is_pentagonal(total) and is_pentagonal(difference):
                return number, current_number
        pentagonal_numbers.append(current_number)


def answer():
    pair = pentagonal_number_pair()
    return abs(pair[0] - pair[1])

if __name__ == '__main__':
    print_answer_and_elapsed_time(answer)
