{- |
Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
the sum of the even-valued terms.
-}

module Problem2
( answer
, sumEvenFibonacciNumbers
) where

import Helpers.Runtime (printAnswerAndElapsedTime)

fibs :: [Int]
fibs = 1:2:(zipWith (+) fibs $ tail fibs)

sumEvenFibonacciNumbers :: Int -> Int
sumEvenFibonacciNumbers maximum =
    sum $ takeWhile (<= maximum) $ filter even fibs

answer :: Int
answer = sumEvenFibonacciNumbers 4000000

main = printAnswerAndElapsedTime answer
