{- |
Problem 45 - Triangular, Pentagonal, Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle        T_n=n(n+1)/2        1, 3, 6, 10, 15, ...
Pentagonal      P_n=n(3n−1)/2       1, 5, 12, 22, 35, ...
Hexagonal       H_n=n(2n−1)         1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
-}

module Problem45
( answer
, hexagonalNumbers
) where

import Helpers.Numbers (isTriangular, isPentagonal)
import Helpers.Runtime (printAnswerAndElapsedTime)

hexagonalNumbers :: [Int]
hexagonalNumbers = map (\n -> n * (2 * n - 1)) [1..]

answer :: Int
answer = head $ dropWhile (<= 40755) $ filter (\n -> isPentagonal n && isTriangular n) hexagonalNumbers

main = printAnswerAndElapsedTime answer
